name: DevOps CICD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Linter
        uses: github/super-linter@v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: iranak
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Buildx
        id: docker_build
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: iranak/devops-ci-cd:latest